name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: Version
        required: true
        type: choice
        options:
          - patch
          - minor
          - major

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
      - run: yarn install --immutable
      - run: yarn version -i '${{ github.event.inputs.version }}'
      - run: yarn npm publish
        env:
          YARN_NPM_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Git commit, tag, and push
        run: |
          git add package.json
          version="$(node -p "require('./package.json').version")"
          git config user.name "${{ github.actor }}"
          git config user.email '${{ github.actor }}@users.noreply.github.com'
          git commit -m "Release v$version"
          git tag -a "v$version" -m "Release v$version"
          git push --follow-tags
